version: '2'
services:
  curator-plus:
    image: eason02/curator-plus:5.2.0
    container_name: curator-plus-5.2.0
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name
    restart: always
    environment:
      - env=prod
    volumes:
      - /var/log/curator/:/var/log/curator/
    logging:
      driver: json-file
      options:
        max-file: '5'
        max-size: 10m
    network_mode: host
